name: build-and-test-web

on:
  push:
    branches: [ "main" ]
    paths:
        - cmd/web/**
        - pkg/**
  pull_request:
    branches: [ "main" ]
    paths:
        - cmd/web/**
        - pkg/**

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: GOOS=js GOARCH=wasm go build -v ./cmd/web

