name: build-and-test

on:
  push:
    branches: [ "main" ]
    paths:
        - '**.go'
        - pkg/**
  pull_request:
    branches: [ "main" ]
    paths:
        - '**.go'
        - pkg/**

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install ebiten dependencies
      run: >
        sudo apt install -y
        libc6-dev 
        libgl1-mesa-dev 
        libxcursor-dev 
        libxi-dev 
        libxinerama-dev 
        libxrandr-dev 
        libxxf86vm-dev 
        libasound2-dev 
        pkg-config

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...
