name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - name: Install ALSA dependencies
        run: sudo apt-get install -y libasound2-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.7
          skip-cache: true

